# -*- coding: utf-8 -*-
"""Testing Sugeno.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11nIzgzQUSPsKoRPFi_ECWU_xIkOKXfYq
"""

pip install pyrebase4

pip install scikit-fuzzy

pip install simpful

import numpy as np
import pyrebase
import skfuzzy as fuzz
from skfuzzy import control as ctrl
from simpful import *
import matplotlib.pyplot as plt
import pandas as pd
import csv

#config
firebaseConfig = {
    "apiKey": "AIzaSyDLU6K6Y3L1gnhq121EGvSniTicrei34kw",
    "authDomain": "androidtofirebase-8ef1d.firebaseapp.com",
    "databaseURL": "https://androidtofirebase-8ef1d-default-rtdb.asia-southeast1.firebasedatabase.app",
    "projectId": "androidtofirebase-8ef1d",
    "storageBucket": "androidtofirebase-8ef1d.appspot.com",
    "messagingSenderId": "663897199193",
    "appId": "1:663897199193:web:fe01eab1e20c3d53f91748",
    "measurementId": "G-S2EYD15CSY"
};

fb = pyrebase.initialize_app(firebaseConfig)
db = fb.database()
Air = db.child("Uji").child("Air").get().val() # a.val()
Wind = db.child("Uji").child("Wind").get().val() # a.val()

print(Air, Wind)

df_awal = pd.read_csv('Tes.csv', sep=';')
print(df_awal)

df = pd.read_csv('Tes.csv', sep=';', usecols= ['QV','TK'])
print(df)

Vpr = float(df.iloc[15, 0])
Clo = float(df.iloc[15, 1])
print(Vpr)
print(Clo)

db.child("Uji").child('Vapor').set(Vpr)
db.child("Uji").child('Cloud').set(Clo)

suhu = ctrl.Antecedent(np.arange(0, 38.5, 0.5), 'Temperatur') # dari user
uap = ctrl.Antecedent(np.arange(0, 0.0185, 0.0005), 'Water Vapor') # nc file
angin = ctrl.Antecedent(np.arange(0, 13.5, 0.5), 'Kecepatan') # dari user
cloud = ctrl.Antecedent(np.arange(0, 28.5, 0.5), 'Awan') # nc file
output = ctrl.Consequent(np.arange(0, 40.5, 0.5), 'output')

sdingin = fuzz.trapmf(suhu.universe, [0, 0, 18.6, 23.2])
snormal = fuzz.trimf(suhu.universe, [18.6, 23.2, 27.8])
shangat = fuzz.trapmf(suhu.universe, [23.2, 27.8, 38, 38])


urendah = fuzz.trapmf(uap.universe, [0, 0, 0.01, 0.013])
usedang = fuzz.trimf(uap.universe, [0.01, 0.013, 0.016])
utinggi = fuzz.trapmf(uap.universe, [0.013, 0.016, 0.0185, 0.0185])


apelan = fuzz.trapmf(angin.universe, [0, 0, 5.5, 7.9])
asedang = fuzz.trapmf(angin.universe, [5.5, 7.9, 10.7, 10.8])
akencang = fuzz.trapmf(angin.universe, [10.7, 10.8, 13.8, 13.8])

adingin = fuzz.trapmf(cloud.universe, [0, 0, 21, 23])
anormal = fuzz.trimf(cloud.universe, [21, 23, 25])
ahangat = fuzz.trapmf(cloud.universe, [23, 25, 28, 28])

C = 9
J = 19
S = 29
T = 30
# Visualize these universes and membership functions
fig, (ax0, ax1, ax2, ax3, ax4) = plt.subplots(nrows=5, figsize=(8, 8))

ax0.plot(suhu.universe, sdingin, 'b', linewidth=1.5, label='Dingin')
ax0.plot(suhu.universe, snormal, 'g', linewidth=1.5, label='Normal')
ax0.plot(suhu.universe, shangat, 'r', linewidth=1.5, label='Hangat')

ax0.set_title('Suhu Permukaan (°C)')
ax0.legend()

ax1.plot(uap.universe, urendah, 'b', linewidth=1.5, label='Rendah')
ax1.plot(uap.universe, usedang, 'g', linewidth=1.5, label='Sedang')
ax1.plot(uap.universe, utinggi, 'r', linewidth=1.5, label='Tinggi')

ax1.set_title('Uap Air (kg/m³)')
ax1.legend()

ax2.plot(angin.universe, apelan, 'b', linewidth=1.5, label='Rendah')
ax2.plot(angin.universe, asedang, 'g', linewidth=1.5, label='Sedang')
ax2.plot(angin.universe, akencang, 'r', linewidth=1.5, label='Tinggi')

ax2.set_title('Kecepatan Angin (m/s)')
ax2.legend()

ax3.plot(cloud.universe, adingin, 'b', linewidth=1.5, label='Dingin')
ax3.plot(cloud.universe, anormal, 'g', linewidth=1.5, label='Normal')
ax3.plot(cloud.universe, ahangat, 'r', linewidth=1.5, label='Hangat')

ax3.set_title('Suhu ketinggian 850 Milibar (°C)')
ax3.legend()


ax4.plot([9, 9], [0, C], 'b', linewidth=1.5, label='Cerah')
ax4.plot([19, 19], [0, J], 'g', linewidth=1.5, label='Jarang')
ax4.plot([29, 29], [0, S], 'r', linewidth=1.5, label='Sedang')
ax4.plot([30, 30], [0, T], 'y', linewidth=1.5, label='Tebal')

ax4.set_title('Output')
ax4.legend()

# Turn off top/right axes
for ax in (ax0, ax1, ax2, ax3):
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.get_xaxis().tick_bottom()
    ax.get_yaxis().tick_left()

plt.tight_layout()
plt.show()

FS = FuzzySystem()

# Define fuzzy sets and linguistic variables
S_1 = FuzzySet(points=[[0.,  1.], [18.6, 1.], [23.2, 0.]], term="Dingin")
S_2 = FuzzySet(points=[[18.6, 0.], [23.2, 1.], [27.8, 0.]], term="Normal")
S_3 = FuzzySet(points=[[23.2, 0.], [27.8, 1.], [38., 1.]], term="Hangat")
FS.add_linguistic_variable("suhu", LinguisticVariable([S_1, S_2, S_3], concept="suhu"))

L_1 = FuzzySet(points=[[0.,  1.], [0.01, 1.], [0.013, 0.]], term="Rendah")
L_2 = FuzzySet(points=[[0.01, 0.], [0.013, 1.], [0.016, 0.]], term="Sedang")
L_3 = FuzzySet(points=[[0.013, 0.], [0.016, 1.], [0.0185, 1.]], term="Tinggi")
FS.add_linguistic_variable("vapor", LinguisticVariable([L_1, L_2, L_3], concept="vapor"))


A_1 = FuzzySet(points=[[0.,  1.], [5.5, 1.], [7.9, 0.]], term="Pelan")
A_2 = FuzzySet(points=[[5.5, 0.], [7.9, 1.], [10.7, 1.], [10.8, 0.]], term="Sedang")
A_3 = FuzzySet(points=[[10.7, 0.], [10.8, 1.], [13.8, 1.]], term="Kencang")
FS.add_linguistic_variable("angin", LinguisticVariable([A_1, A_2, A_3], concept="angin"))

C_1 = FuzzySet(points=[[0.,  1.], [21., 1.], [23., 0.]], term="Dingin")
C_2 = FuzzySet(points=[[21., 0.], [23., 1.], [25., 0.]], term="Normal")
C_3 = FuzzySet(points=[[23., 0.], [25., 1.], [28., 1.]], term="Hangat")
FS.add_linguistic_variable("cloud", LinguisticVariable([C_1, C_2, C_3], concept="cloud"))

"""O_1 = FuzzySet(points=[[0.,  1.], [3., 1.], [5., 0.]], term="Cerah")
O_2 = FuzzySet(points=[[3., 0.], [4., 0.], [10., 1.], [15., 0.]], term="Jarang")
O_3 = FuzzySet(points=[[11., 0.], [17., 0.], [20., 1.], [24., 0.]], term="Sedang")
O_4 = FuzzySet(points=[[19., 0.], [27., 0.], [30., 1.], [34., 1.]], term="Tebal")

FS.add_linguistic_variable("output", LinguisticVariable([O_1, O_2, O_3, O_4]))"""

# # Define output crisp values
# FS.set_crisp_output_value("small", 5)
# FS.set_crisp_output_value("average", 15)
# FS.set_output_function("generous", "Food+Service+5")
FS.set_crisp_output_value("Cerah", 9) 
FS.set_crisp_output_value("Jarang", 19)
FS.set_crisp_output_value("Sedang", 29) 
FS.set_crisp_output_value("Tebal", 30)

#FS.set_output_function("generous", "suhu+vapor+angin+cloud+5")

# # Define fuzzy rules
# R1 = "IF (Service IS poor) OR (Food IS rancid) THEN (Tip IS small)"
# R2 = "IF (Service IS good) THEN (Tip IS average)"
# R3 = "IF (Service IS excellent) OR (Food IS delicious) THEN (Tip IS generous)"
# FS.add_rules([R1, R2, R3])


R1 = "IF(suhu IS Dingin) AND (vapor IS Rendah) AND (angin IS Pelan) AND (cloud IS Dingin) THEN (output IS Jarang)"
R2 = "IF(suhu IS Dingin) AND (vapor IS Rendah) AND (angin IS Pelan) AND (cloud IS Normal) THEN (output IS Sedang)"
R3 = "IF(suhu IS Dingin) AND (vapor IS Rendah) AND (angin IS Pelan) AND (cloud IS Hangat) THEN (output IS Jarang)"
R4 = "IF(suhu IS Dingin) AND (vapor IS Rendah) AND (angin IS Sedang) AND (cloud IS Dingin) THEN (output IS Jarang)"
R5 = "IF(suhu IS Dingin) AND (vapor IS Rendah) AND (angin IS Sedang) AND (cloud IS Normal) THEN (output IS Cerah)"
R6 = "IF(suhu IS Dingin) AND (vapor IS Rendah) AND (angin IS Sedang) AND (cloud IS Hangat) THEN (output IS Cerah)"
R7 = "IF(suhu IS Dingin) AND (vapor IS Rendah) AND (angin IS Kencang) AND (cloud IS Dingin) THEN (output IS Jarang)"
R8 = "IF(suhu IS Dingin) AND (vapor IS Rendah) AND (angin IS Kencang) AND (cloud IS Normal) THEN (output IS Cerah)"
R9 = "IF(suhu IS Dingin) AND (vapor IS Rendah) AND (angin IS Kencang) AND (cloud IS Hangat) THEN (output IS Cerah)"

R10 = "IF(suhu IS Dingin) AND (vapor IS Sedang) AND (angin IS Pelan) AND (cloud IS Dingin) THEN (output IS Sedang)"
R11 = "IF(suhu IS Dingin) AND (vapor IS Sedang) AND (angin IS Pelan) AND (cloud IS Normal) THEN (output IS Jarang)"
R12 = "IF(suhu IS Dingin) AND (vapor IS Sedang) AND (angin IS Pelan) AND (cloud IS Hangat) THEN (output IS Cerah)"
R13 = "IF(suhu IS Dingin) AND (vapor IS Sedang) AND (angin IS Sedang) AND (cloud IS Dingin) THEN (output IS Jarang)"
R14 = "IF(suhu IS Dingin) AND (vapor IS Sedang) AND (angin IS Sedang) AND (cloud IS Normal) THEN (output IS Jarang)"
R15 = "IF(suhu IS Dingin) AND (vapor IS Sedang) AND (angin IS Sedang) AND (cloud IS Hangat) THEN (output IS Cerah)"
R16 = "IF(suhu IS Dingin) AND (vapor IS Sedang) AND (angin IS Kencang) AND (cloud IS Dingin) THEN (output IS Jarang)"
R17 = "IF(suhu IS Dingin) AND (vapor IS Sedang) AND (angin IS Kencang) AND (cloud IS Normal) THEN (output IS Cerah)"
R18 = "IF(suhu IS Dingin) AND (vapor IS Sedang) AND (angin IS Kencang) AND (cloud IS Hangat) THEN (output IS Cerah)"

R19 = "IF(suhu IS Dingin) AND (vapor IS Tinggi) AND (angin IS Pelan) AND (cloud IS Dingin) THEN (output IS Sedang)"
R20 = "IF(suhu IS Dingin) AND (vapor IS Tinggi) AND (angin IS Pelan) AND (cloud IS Normal) THEN (output IS Jarang)"
R21 = "IF(suhu IS Dingin) AND (vapor IS Tinggi) AND (angin IS Pelan) AND (cloud IS Hangat) THEN (output IS Jarang)"
R22 = "IF(suhu IS Dingin) AND (vapor IS Tinggi) AND (angin IS Sedang) AND (cloud IS Dingin) THEN (output IS Sedang)"
R23 = "IF(suhu IS Dingin) AND (vapor IS Tinggi) AND (angin IS Sedang) AND (cloud IS Normal) THEN (output IS Jarang)"
R24 = "IF(suhu IS Dingin) AND (vapor IS Tinggi) AND (angin IS Sedang) AND (cloud IS Hangat) THEN (output IS Cerah)"
R25 = "IF(suhu IS Dingin) AND (vapor IS Tinggi) AND (angin IS Kencang) AND (cloud IS Dingin) THEN (output IS Jarang)"
R26 = "IF(suhu IS Dingin) AND (vapor IS Tinggi) AND (angin IS Kencang) AND (cloud IS Normal) THEN (output IS Jarang)"
R27 = "IF(suhu IS Dingin) AND (vapor IS Tinggi) AND (angin IS Kencang) AND (cloud IS Hangat) THEN (output IS Cerah)"

R28 = "IF(suhu IS Normal) AND (vapor IS Rendah) AND (angin IS Pelan) AND (cloud IS Dingin) THEN (output IS Jarang)"
R29 = "IF(suhu IS Normal) AND (vapor IS Rendah) AND (angin IS Pelan) AND (cloud IS Normal) THEN (output IS Cerah)"
R30 = "IF(suhu IS Normal) AND (vapor IS Rendah) AND (angin IS Pelan) AND (cloud IS Hangat) THEN (output IS Cerah)"
R31 = "IF(suhu IS Normal) AND (vapor IS Rendah) AND (angin IS Sedang) AND (cloud IS Dingin) THEN (output IS Jarang)"
R32 = "IF(suhu IS Normal) AND (vapor IS Rendah) AND (angin IS Sedang) AND (cloud IS Normal) THEN (output IS Cerah)"
R33 = "IF(suhu IS Normal) AND (vapor IS Rendah) AND (angin IS Sedang) AND (cloud IS Hangat) THEN (output IS Cerah)"
R34 = "IF(suhu IS Normal) AND (vapor IS Rendah) AND (angin IS Kencang) AND (cloud IS Dingin) THEN (output IS Jarang)"
R35 = "IF(suhu IS Normal) AND (vapor IS Rendah) AND (angin IS Kencang) AND (cloud IS Normal) THEN (output IS Jarang)"
R36 = "IF(suhu IS Normal) AND (vapor IS Rendah) AND (angin IS Kencang) AND (cloud IS Hangat) THEN (output IS Cerah)"

R37 = "IF(suhu IS Normal) AND (vapor IS Sedang) AND (angin IS Pelan) AND (cloud IS Dingin) THEN (output IS Jarang)"
R38 = "IF(suhu IS Normal) AND (vapor IS Sedang) AND (angin IS Pelan) AND (cloud IS Normal) THEN (output IS Jarang)"
R39 = "IF(suhu IS Normal) AND (vapor IS Sedang) AND (angin IS Pelan) AND (cloud IS Hangat) THEN (output IS Cerah)"
R40 = "IF(suhu IS Normal) AND (vapor IS Sedang) AND (angin IS Sedang) AND (cloud IS Dingin) THEN (output IS Jarang)"
R41 = "IF(suhu IS Normal) AND (vapor IS Sedang) AND (angin IS Sedang) AND (cloud IS Normal) THEN (output IS Jarang)"
R42 = "IF(suhu IS Normal) AND (vapor IS Sedang) AND (angin IS Sedang) AND (cloud IS Hangat) THEN (output IS Cerah)"
R43 = "IF(suhu IS Normal) AND (vapor IS Sedang) AND (angin IS Kencang) AND (cloud IS Dingin) THEN (output IS Jarang)"
R44 = "IF(suhu IS Normal) AND (vapor IS Sedang) AND (angin IS Kencang) AND (cloud IS Normal) THEN (output IS Cerah)"
R45 = "IF(suhu IS Normal) AND (vapor IS Sedang) AND (angin IS Kencang) AND (cloud IS Hangat) THEN (output IS Cerah)"

R46 = "IF(suhu IS Normal) AND (vapor IS Tinggi) AND (angin IS Pelan) AND (cloud IS Dingin) THEN (output IS Tebal)"
R47 = "IF(suhu IS Normal) AND (vapor IS Tinggi) AND (angin IS Pelan) AND (cloud IS Normal) THEN (output IS Sedang)"
R48 = "IF(suhu IS Normal) AND (vapor IS Tinggi) AND (angin IS Pelan) AND (cloud IS Hangat) THEN (output IS Jarang)"
R49 = "IF(suhu IS Normal) AND (vapor IS Tinggi) AND (angin IS Sedang) AND (cloud IS Dingin) THEN (output IS Sedang)"
R50 = "IF(suhu IS Normal) AND (vapor IS Tinggi) AND (angin IS Sedang) AND (cloud IS Normal) THEN (output IS Jarang)"
R51 = "IF(suhu IS Normal) AND (vapor IS Tinggi) AND (angin IS Sedang) AND (cloud IS Hangat) THEN (output IS Jarang)"
R52 = "IF(suhu IS Normal) AND (vapor IS Tinggi) AND (angin IS Kencang) AND (cloud IS Dingin) THEN (output IS Jarang)"
R53 = "IF(suhu IS Normal) AND (vapor IS Tinggi) AND (angin IS Kencang) AND (cloud IS Normal) THEN (output IS Cerah)"
R54 = "IF(suhu IS Normal) AND (vapor IS Tinggi) AND (angin IS Kencang) AND (cloud IS Hangat) THEN (output IS Cerah)"

R55 = "IF(suhu IS Hangat) AND (vapor IS Rendah) AND (angin IS Pelan) AND (cloud IS Dingin) THEN (output IS Jarang)"
R56 = "IF(suhu IS Hangat) AND (vapor IS Rendah) AND (angin IS Pelan) AND (cloud IS Normal) THEN (output IS Jarang)"
R57 = "IF(suhu IS Hangat) AND (vapor IS Rendah) AND (angin IS Pelan) AND (cloud IS Hangat) THEN (output IS Cerah)"
R58 = "IF(suhu IS Hangat) AND (vapor IS Rendah) AND (angin IS Sedang) AND (cloud IS Dingin) THEN (output IS Jarang)"
R59 = "IF(suhu IS Hangat) AND (vapor IS Rendah) AND (angin IS Sedang) AND (cloud IS Normal) THEN (output IS Cerah)"
R60 = "IF(suhu IS Hangat) AND (vapor IS Rendah) AND (angin IS Sedang) AND (cloud IS Hangat) THEN (output IS Cerah)"
R61 = "IF(suhu IS Hangat) AND (vapor IS Rendah) AND (angin IS Kencang) AND (cloud IS Dingin) THEN (output IS Jarang)"
R62 = "IF(suhu IS Hangat) AND (vapor IS Rendah) AND (angin IS Kencang) AND (cloud IS Normal) THEN (output IS Cerah)"
R63 = "IF(suhu IS Hangat) AND (vapor IS Rendah) AND (angin IS Kencang) AND (cloud IS Hangat) THEN (output IS Cerah)"

R64 = "IF(suhu IS Hangat) AND (vapor IS Sedang) AND (angin IS Pelan) AND (cloud IS Dingin) THEN (output IS Jarang)"
R65 = "IF(suhu IS Hangat) AND (vapor IS Sedang) AND (angin IS Pelan) AND (cloud IS Normal) THEN (output IS Jarang)"
R66 = "IF(suhu IS Hangat) AND (vapor IS Sedang) AND (angin IS Pelan) AND (cloud IS Hangat) THEN (output IS Cerah)"
R67 = "IF(suhu IS Hangat) AND (vapor IS Sedang) AND (angin IS Sedang) AND (cloud IS Dingin) THEN (output IS Jarang)"
R68 = "IF(suhu IS Hangat) AND (vapor IS Sedang) AND (angin IS Sedang) AND (cloud IS Normal) THEN (output IS Cerah)"
R69 = "IF(suhu IS Hangat) AND (vapor IS Sedang) AND (angin IS Sedang) AND (cloud IS Hangat) THEN (output IS Cerah)"
R70 = "IF(suhu IS Hangat) AND (vapor IS Sedang) AND (angin IS Kencang) AND (cloud IS Dingin) THEN (output IS Jarang)"
R71 = "IF(suhu IS Hangat) AND (vapor IS Sedang) AND (angin IS Kencang) AND (cloud IS Normal) THEN (output IS Cerah)"
R72 = "IF(suhu IS Hangat) AND (vapor IS Sedang) AND (angin IS Kencang) AND (cloud IS Hangat) THEN (output IS Cerah)"

R73 = "IF(suhu IS Hangat) AND (vapor IS Tinggi) AND (angin IS Pelan) AND (cloud IS Dingin) THEN (output IS Tebal)"
R74 = "IF(suhu IS Hangat) AND (vapor IS Tinggi) AND (angin IS Pelan) AND (cloud IS Normal) THEN (output IS Sedang)"
R75 = "IF(suhu IS Hangat) AND (vapor IS Tinggi) AND (angin IS Pelan) AND (cloud IS Hangat) THEN (output IS Cerah)"
R76 = "IF(suhu IS Hangat) AND (vapor IS Tinggi) AND (angin IS Sedang) AND (cloud IS Dingin) THEN (output IS Tebal)"
R77 = "IF(suhu IS Hangat) AND (vapor IS Tinggi) AND (angin IS Sedang) AND (cloud IS Normal) THEN (output IS Jarang)"
R78 = "IF(suhu IS Hangat) AND (vapor IS Tinggi) AND (angin IS Sedang) AND (cloud IS Hangat) THEN (output IS Cerah)"
R79 = "IF(suhu IS Hangat) AND (vapor IS Tinggi) AND (angin IS Kencang) AND (cloud IS Dingin) THEN (output IS Jarang)"
R80 = "IF(suhu IS Hangat) AND (vapor IS Tinggi) AND (angin IS Kencang) AND (cloud IS Normal) THEN (output IS Jarang)"
R81 = "IF(suhu IS Hangat) AND (vapor IS Tinggi) AND (angin IS Kencang) AND (cloud IS Hangat) THEN (output IS Cerah)"


FS.add_rules([R1, R2, R3, R4, R5, R6, R7, R8, R9,R10, R11, R12, R13, R14, R15, R16, R17, R18, R19,R20, R21, R22, R23, R24, R25, R26, R27, R28, R29, R30, R31, R32, R33, R34, R35, R36, R37, R38, R39,R40, R41, R42, R43, R44, R45, R46, R47, R48, R49,R50, R51, R52, R53, R54, R55, R56, R57, R58, R59,R60, R61, R62, R63, R64, R65, R66, R67, R68, R69,R70, R71, R72, R73, R74, R75, R76, R77, R78, R79, R80, R81])


# Atur nilai inputnya
FS.set_variable("suhu", Air)
FS.set_variable("vapor", Vpr)
FS.set_variable("angin", Wind)
FS.set_variable("cloud", Clo)


# Running inferensi Sugeno dan hasil output                       
print(FS.Sugeno_inference(["output"]))

# CRUD ke firebase
db.child("Uji").child('Output').set(FS.Sugeno_inference(["output"])['output'])

Hasil = db.child("Uji").child("Output").get().val() # a.val()
print(Hasil)

hari_ini = (Hasil)
if(hari_ini <= 9):
  print("Cerah")
  db.child("Uji").child("Sugeno").set("Cerah")
elif(hari_ini > 9 and hari_ini <= 19.0):
  print("Awan Tumbuh Jarang")
  db.child("Uji").child("Sugeno").set("Awan Tumbuh Jarang")
elif(hari_ini > 19.0 and hari_ini <= 29.0):
  print("Awan Tumbuh Sedang")
  db.child("Uji").child("Sugeno").set("Awan Tumbuh Sedang")
elif(hari_ini > 29.0):
  print("Awan Tumbuh Tebal")
  db.child("Uji").child("Sugeno").set("Awan Tumbuh Tebal")